### ISSUE TITLE
获取Token报错

### ISSUE THREAD

**Issue by jxcia** [TencentBlueKing/iam-go-sdk#5]
![image](https://user-images.githubusercontent.com/30133649/126036618-40b05f5c-520b-4e86-a29f-34b22a747e01.png)
具体报错信息：
gorequest errors=`[invalid character '<' looking for beginning of value]`

不知道哪里错了。

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/iam-go-sdk/blob/master/examples/quickstart/main.go#L38

根据例子, 配置下logger(level=debug), 然后重新请求, 看下打印debug信息

**Comment by jxcia** [comment]
现在就是debug日志，看情况应该是没获取到接口，返回的404页面，导致无法解析json数据。不知道是哪里设置错了。

**Comment by jxcia** [comment]
API server listening at: 127.0.0.1:2345
2021-07-19T09:55:24+08:00 info layer=debugger launching process with args: [e:\go\bk-sdk\__debug_bin]
2021-07-19T09:55:24+08:00 warning layer=debugger could not set asyncpreemptoff <nil>
2021-07-19T09:55:24+08:00 debug layer=debugger continuing
time="2021-07-19T09:55:24+08:00" level=debug msg="calling IAM.is_allowed(request)......"
time="2021-07-19T09:55:24+08:00" level=debug msg="the request: {bk_paas {user admin} {access_developer_center} []}"
time="2021-07-19T09:55:24+08:00" level=debug msg="do http request: method=`POST`, url=`http://paas.xxxx.com:80/o/bk_iam//api/v1/policy/query`, data=`{bk_paas {user admin} {access_developer_center} []}`"
time="2021-07-19T09:55:24+08:00" level=error msg="[http request fail] -! status=`403`, errs=`[invalid character '<' looking for beginning of value]`, request_id=`14dd89b1c7564dd38285bf3e152a2123`, request=`curl -X 'POST' -d '{\"action\":{\"id\":\"access_developer_center\"},\"resources\":[],\"subject\":{\"id\":\"admin\",\"type\":\"user\"},\"system\":\"bk_paas\"}' -H 'Content-Type: application/json' -H 'X-Bk-App-Code: bk_iam' -H 'X-Bk-App-Secret: ea7ed263-2d0b-4772-be57-f79750895af7' -H 'X-Bk-Iam-Version: 1' 'http://paas.xxxx.com:80/o/bk_iam//api/v1/policy/query'`"
time="2021-07-19T09:55:24+08:00" level=debug msg="http request result: response[code=`0`, message=``, data=``]"
time="2021-07-19T09:55:24+08:00" level=debug msg="http request took 226 ms"
isAllowed: false gorequest errors=`[invalid character '<' looking for beginning of value]`
time="2021-07-19T09:55:24+08:00" level=error msg="do policy query fail! err=%!w(*errors.errorString=&{gorequest errors=`[invalid character '<' looking for beginning of value]`})"

**Comment by wklken** [comment]
`http://paas.xxxx.com:80/o/bk_iam//api/v1/policy/query`

这个地址需要改成自己环境的权限中心后台地址

**Comment by wklken** [comment]
http://paas.xxxx.com:80/o/bk_iam//api/v1/policy/quer

这里的host, 应该是 权限中心的后台地址(如果是蓝鲸部署, 用运维脚本找下 bkiam consul地址)
而不是SaaS 地址(管理页面)
